In [61]:
import pandas as pd

df = pd.read_csv('data.csv')

In [35]:
df.head()

,order_id,order_date,customer_id,region,sales_channel,product,category,quantity,unit_price,discount_rate,revenue,unit_cost,rating,returned,delivery_days
0,ORD-0001,2025-11-24,CUST-014,Central,Online,Pen Set,Stationery,1,5.25,0.05,4.99,2.83,NaN,No,1.0
1,ORD-0002,2025-01-16,CUST-026,Central,Store,Pen Set,Stationery,4,5.25,0.00,21.00,3.16,2.0,No,5.0
2,ORD-0003,2025-01-04,CUST-044,North,Online,Water Bottle,Accessories,7,14.00,0.05,93.10,7.65,3.0,No,6.0
3,ORD-0004,2025-06-26,CUST-049,North,Marketplace,Desk Lamp,Home,1,27.50,0.10,24.75,16.74,5.0,No,6.0
4,ORD-0005,2025-10-23,CUST-011,South,Online,Backpack,Accessories,2,38.00,0.00,76.00,24.27,5.0,No,8.0

In [ ]:
df.tail()

In [ ]:
df.info()

In [ ]:
df.describe()

In [23]:
df.index

RangeIndex(start=0, stop=200, step=1)

In [38]:
len(df['region'])

200

In [46]:
df['region'].value_counts()

region
Central    45
South      41
East       41
West       39
North      34
Name: count, dtype: int64

In [49]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'region', 'sales_channel',
       'product', 'category', 'quantity', 'unit_price', 'discount_rate',
       'revenue', 'unit_cost', 'rating', 'returned', 'delivery_days'],
      dtype='str')

In [53]:
df[["region", "product"]]

      region         product
0    Central         Pen Set
1    Central         Pen Set
2      North    Water Bottle
3      North       Desk Lamp
4      South        Backpack
..       ...             ...
195     West             Mug
196     West         Pen Set
197  Central  Wireless Mouse
198    South         Pen Set
199    North         Pen Set

[200 rows x 2 columns]

In [63]:
df.iloc[10][["region", "product"]]

region     Central
product    Pen Set
Name: 10, dtype: object

In [71]:
df.head()

,order_id,order_date,customer_id,region,sales_channel,product,category,quantity,unit_price,discount_rate,revenue,unit_cost,rating,returned,delivery_days
0,ORD-0001,2025-11-24,CUST-014,Central,Online,Pen Set,Stationery,1,5.25,0.05,4.99,2.83,NaN,No,1.0
1,ORD-0002,2025-01-16,CUST-026,Central,Store,Pen Set,Stationery,4,5.25,0.00,21.00,3.16,2.0,No,5.0
2,ORD-0003,2025-01-04,CUST-044,North,Online,Water Bottle,Accessories,7,14.00,0.05,93.10,7.65,3.0,No,6.0
3,ORD-0004,2025-06-26,CUST-049,North,Marketplace,Desk Lamp,Home,1,27.50,0.10,24.75,16.74,5.0,No,6.0
4,ORD-0005,2025-10-23,CUST-011,South,Online,Backpack,Accessories,2,38.00,0.00,76.00,24.27,5.0,No,8.0

In [ ]:
df[(df['region'] == 'East') & (df['revenue'] > 30)]